# Generated by Django 4.2.3 on 2023-07-28 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('personality', models.TextField()),
                ('background', models.TextField()),
                ('goals', models.TextField()),
                ('strengths', models.TextField()),
                ('weakness', models.TextField()),
                ('skills', models.TextField()),
                ('hobbies', models.TextField()),
                ('backstory', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Lore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_name', models.CharField(max_length=225)),
                ('overview', models.TextField()),
                ('geography', models.TextField()),
                ('culture_society', models.TextField()),
                ('history', models.TextField()),
                ('magic_tech', models.TextField()),
                ('politics', models.TextField()),
                ('economy', models.TextField()),
                ('creatures', models.TextField()),
                ('language', models.TextField()),
                ('arts', models.TextField()),
                ('miscellaneous', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.TextField()),
                ('author', models.CharField(max_length=225)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('image', models.FileField(blank=True, upload_to='')),
                ('characters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.character')),
                ('lore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.lore')),
            ],
        ),
    ]
