# Generated by Django 4.2.3 on 2023-07-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_world_name_lore_worldname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lore',
            old_name='culture_society',
            new_name='culturesociety',
        ),
        migrations.RenameField(
            model_name='lore',
            old_name='magic_tech',
            new_name='magictech',
        ),
    ]
