# Generated by Django 4.2.3 on 2023-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_culture_society_lore_culturesociety_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date_ended',
            new_name='datestart',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_started',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='characters',
        ),
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(to='blog.character'),
        ),
    ]
